// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHDOwYWK3jDz_a_rIDAu8eQmnu6hmW1rM',
    appId: '1:683073265908:web:5e520ae3fce253493c3ea1',
    messagingSenderId: '683073265908',
    projectId: 'flutter-employment-management',
    authDomain: 'flutter-employment-management.firebaseapp.com',
    storageBucket: 'flutter-employment-management.appspot.com',
    measurementId: 'G-K377WKRRRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0kAAeo-O4apM9Xb_nZ_PF-vQ1KBTI2hk',
    appId: '1:683073265908:android:0eae598655c51a123c3ea1',
    messagingSenderId: '683073265908',
    projectId: 'flutter-employment-management',
    storageBucket: 'flutter-employment-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QkyyCGAPN2myCdxE0-OyYByo-m_4a7U',
    appId: '1:683073265908:ios:5b99107b91c095c53c3ea1',
    messagingSenderId: '683073265908',
    projectId: 'flutter-employment-management',
    storageBucket: 'flutter-employment-management.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEmploymentManagmentSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QkyyCGAPN2myCdxE0-OyYByo-m_4a7U',
    appId: '1:683073265908:ios:c50841d9b24b95693c3ea1',
    messagingSenderId: '683073265908',
    projectId: 'flutter-employment-management',
    storageBucket: 'flutter-employment-management.appspot.com',
    iosBundleId: 'com.example.flutterApplicationEmploymentManagmentSystem.RunnerTests',
  );
}
